apiVersion: v1
kind: Pod
metadata:
  name: env-congigmap
spec:
  containers:
    - name: nginx
      command: [ "/bin/sh", "-c", "env" ]
      image: nginx
      envFrom:
      - configMapRef:
          name: pod-config
  
